# Generated by Django 5.2.9 on 2026-03-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_items_end_date_order_items_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='start_date',
        ),
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
